language: android
jdk:
    - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.3
  - android-24
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+

sudo: false

before_script:
    - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2

script:
  ./gradlew build test